<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net6.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>

    <!-- Force the old .NET 4.8 compiler to use modern C# language features -->
    <LangVersion>latest</LangVersion>

    <!-- Disable these two features for .NET 4.8 to prevent conflicts -->
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Disable the nullable -->
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <!-- Special reference addition for .net framework 4.8-->

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <reference Include="System.Windows.Form"></reference>
    <reference Include="System.Drawing"></reference>
  </ItemGroup>
  
</Project>
